# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartyWWW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='gilSessionMeasurementDescription',
            field=models.CharField(default='Witamy', max_length=1000),
        ),
        migrations.AddField(
            model_name='admindata',
            name='gilSessionMeasurementLengthSecons',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='admindata',
            name='gilSessionTrainingDescription',
            field=models.CharField(default='Witamy', max_length=1000),
        ),
        migrations.AddField(
            model_name='admindata',
            name='gilSessionTrainingLengthSeconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='welcome',
            field=models.CharField(default='Witamy', max_length=1000),
        ),
    ]
