# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartyWWW', '0002_auto_20180117_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('MAN', 'MAN'), ('WOMAN', 'WOMAN')], default='MAN', max_length=10)),
                ('age', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='admindata',
            old_name='gilSessionMeasurementLengthSecons',
            new_name='gilSessionMeasurementLengthSeconds',
        ),
        migrations.AddField(
            model_name='admindata',
            name='redBackgroundTimeSeconds',
            field=models.IntegerField(default=3),
        ),
    ]
