# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartyWWW', '0003_auto_20180117_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='cardSessionMeasurementDescription',
            field=models.CharField(default='Witamy', max_length=1000),
        ),
        migrations.AddField(
            model_name='admindata',
            name='cardSessionMeasurementLengthSeconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='admindata',
            name='cardSessionTrainingDescription',
            field=models.CharField(default='Witamy', max_length=1000),
        ),
        migrations.AddField(
            model_name='admindata',
            name='cardSessionTrainingLengthSeconds',
            field=models.IntegerField(default=60),
        ),
    ]
