# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartyWWW', '0005_player_gilsessiontimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taskNumber', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('solutionTime', models.CharField(max_length=100)),
                ('times', models.CharField(max_length=1000)),
            ],
        ),
    ]
