# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartyWWW', '0006_cardresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='thanks',
            field=models.CharField(default='Dziękujemy', max_length=1000),
        ),
    ]
